### ISSUE TITLE
On node screen should destination and outgoing title be links rather than buttons?

### ISSUE THREAD

**Issue by conradr** [QuestionKey/QuestionKey-Core#27]

**Comment by ShelterJames** [comment]
I would want to discuss this in a wider sense. 

I wouldn't want to replace the buttons as we use buttons everywhere else, so we should be consistent.

However, at the moment someone who sees the title of the destination then has to go and find the right button to press which is an extra step. I would say the text in the "Destination" column should be a link to the destination node, and the text in the "Outgoing Title" column should be a link to the node option - as well as the buttons.

**Comment by ShelterJames** [comment]
> the text in the "Destination" column should be a link to the destination node, and the text in the "Outgoing Title" column should be a link to the node option 

Done.

Closing for now, unless fuller discussion.
